### PR TITLE
Adding ability to specify how the workspace would be name

### PR DESCRIPTION
**Pull request by nick1907**
This path give us ability to specify some masks and patterns in manual view (in Jenkins job configuration). With this path we can easily prepare a global workspace pattern of how the workspace would be named. For instance, if we have only one convention for our workspaces, we don't need to change the workspace name in every job.

### CODE REVIEW

**Comment by p4paul** [comment]
Hi Nick, think you might have forked from dev branch.  The plugin is managed from jenkinsci/p4-plugin:
   https://github.com/jenkinsci/p4-plugin
I'm not a big github user, but will see if I can merge from here.

**Comment by p4paul** [comment]
Looks like you might have accidentally added some of the temporary test data in directory 'tmp-*/'

**Comment by nick1907** [comment]
Sorry for that. I don't know why the test directory is here. I will try to dele it.

**Comment by p4paul** [comment]
Hi Nick,  I'm trying to understand your use case as the change will need to work for other users too.  You can already use ${VAR} in the workspace name and View/Stream fields, so this would allow you to specify mask patterns.  Sorry if I missed the point.

Unfortunately GitHub makes it very difficult for me to see your changes and I will be unable to merge the code from p4paul/p4-jenkins.  Please can you move the changes to a new pull request on jenkinsci/p4-plugin.  Lots of smaller pull requests are easier to manage and see the changes.

In addition, I try to manage issues/SIRs from JIRA; it also gives the opportunity for other users to comment/discuss the changes.  You can get to JIRA from the 'Open Issues' link on the wiki page:
https://wiki.jenkins-ci.org/display/JENKINS/P4+Plugin

**Comment by nick1907** [comment]
Hi Paul,
I thought that the plugin needs have one value in global configuration which can be our workspace map pattern.

Maybe I should show you this in a simple example:
let's assume that our global value for the map pattern is:
String map = "ws";
and our workspace name is: "jenkins_job_ws"
and our mapping configuration in Jenkins job is something like this:
//depot/job/files/... //ws/code/...

Then the result should be something like this: //depot/job/files/... //jenkins_job_ws/code/... (this result is only visible by the p4 plugin, job configuration is still the same).

Do you understand what I mean?

**Comment by nick1907** [comment]
I thin that, this value as a part of jenkins global configuration is better because it's a part of p4-plugin configuration, and you can define it once and use it everywhere. New Jenkins users can have some problems with remembering where they should create a value for mask pattern, and this is why I added it as a part of global p4-plugin configuration.

Maybe I am wrong, please correct me if I miss anything.

**Comment by p4paul** [comment]
The default name is normally `jenkins-${JOB_NAME}-${NODE_NAME}` and used in the view too. e.g.

    //depot/projA/... //jenkins-${JOB_NAME}-${NODE_NAME}/...

You can make all the Freestyle configurations or Pipeline Scripts the same and let Jenkins substitute the ${VAR} variables.  In theory you could use ${P4_CLIENT} in the view too, although I have not tested this:

    //depot/projA/... //${P4_CLIENT}/...

**Comment by nick1907** [comment]
OK, you are right.

Anyway,
I think that the form with //ws/... which will be expanded only in plugin is much more user friendly than the //${P4_CLIENT}/...
My solution doesn't reject your solution, it only extends it.

**Pull request closed without merging**
