### PR TITLE
added new workspace mode - text file with view mappings

### PR DESCRIPTION
**Pull request by hamstergene**
This pull request adds "View Mappings" workspace mode, similar to "Spec file". It pulls a text file from perforce and creates/updates given workspace view with contents from that file, ignoring comments and empty lines.

Some companies only keep view mappings under version control, not whole workspace definition, which allows developers to name their workspaces and local disk locations as they please, instead of forcing them to use hardcoded values from p4s file (or to edit p4s file locally every single time it is updated). And allowing comments inside text mapping file also helps greatly for those who manage it.

I have tested this locally for some time, and it works well, no different from "Spec file" in any way.

My [p5](https://github.com/hamstergene/p5) script which helps working in that style has been starred a few times, so I assume we're not the only ones who do that :)

Would you accept such feature into the primary plugin?

### CODE REVIEW

**Comment by p4paul** [comment]
Hi Eugene,

Thanks for looking at this and taking the time to write the change.

Out of interest did you know about the 'p4 client -t' option?  Your users could use a template workspace with a defined view and use it to create or update another workspace (you can do this in P4V too).

Would it be possible to enhance the change to read normal Perforce Spec files as well?  I noticed that you use ';' for comments, but in the Perforce spec we use '#', perhaps we could add this too.  An alternative might be to extend the existing SpecWorkspaceImpl implementation to read both file types?

In addition I would like to add a functional test for the new/updated type.  If you would like to write one please look at one of the methods from ConnectionTest.java.  Alternatively I would be happy to help, but please could you provide me with a sample View Spec file with a mixture of views and comments to use in the test.

Kind regards,
Paul



> On 26 Mar 2015, at 14:32, Eugene <notifications@github.com> wrote:
> 
> This pull request adds "View Mappings" workspace mode, similar to "Spec file". It pulls a text file from perforce and creates/updates given workspace view with contents from that file, ignoring comments and empty lines.
> 
> Some companies only keep view mappings under version control, not whole workspace definition, which allows developers to name their workspaces and local disk locations as they please, instead of forcing them to use hardcoded values from p4s file (or to edit p4s file locally every single time it is updated).
> 
> I have tested this locally for some time, and it works well, no different from "Spec file" in any way.
> 
> My p5 script which helps working in that style has been starred a few times, so I assume we're not the only ones who do that :)
> 
> Would you accept such feature into the primary plugin?
> 
> You can view, comment on, or merge this pull request online at:
> 
>   https://github.com/p4paul/p4-jenkins/pull/13
> 
> Commit Summary
> 
> 	• added new workspace mode - text file with view mappings
> File Changes
> 
> 	• M README.md (4)
> 	• A src/main/java/org/jenkinsci/plugins/p4/workspace/ViewMappingsImpl.java (160)
> 	• M src/main/java/org/jenkinsci/plugins/p4/workspace/WorkspaceType.java (2)
> 	• A src/main/resources/org/jenkinsci/plugins/p4/workspace/ViewMappingsImpl/config.jelly (15)
> 	• A src/main/resources/org/jenkinsci/plugins/p4/workspace/ViewMappingsImpl/help-charset.html (6)
> 	• A src/main/resources/org/jenkinsci/plugins/p4/workspace/ViewMappingsImpl/help-name.html (11)
> 	• A src/main/resources/org/jenkinsci/plugins/p4/workspace/ViewMappingsImpl/help-specpath.html (9)
> Patch Links:
> 
> 	• https://github.com/p4paul/p4-jenkins/pull/13.patch
> 	• https://github.com/p4paul/p4-jenkins/pull/13.diff
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by hamstergene** [comment]
Hi Paul,

Template workspaces don't work for us for a couple of reasons — specs need to be under version control to integrate changes between branches into them, comments are vital as they are rather large and need explanations what goes where, etc.

Your suggestions about merging this with SpecFile just gave me an idea... What if I instead extend SpecFile mode with a filter script command? I imagine this will be the most flexible — anyone can use whatever spec format they are used to, or even many of them, and write a very simple filter script to convert it to the standard p4s; or leave script command field empty and use p4s directly. And this will avoid complicating the plugin with a new mode which largely duplicates SpecFile in functionality&tests anyway.

BTW, is this the right repo to send pull requests to? I see this one has version 1.0.11 while jenkinsci/p4-jenkins is at 1.2.0.

**Comment by p4paul** [comment]
Hi Eugene,

The filter script command does seem like an interesting idea.  How would you provide the Workspace name if your text file only has a View (would you parse it from the Right Hand Side part of the mapping?).

You are correct p4paul/p4-jenkins is an old development repo the active repo is jenkinsci/p4-jenkins.  I do most of my development in the Perforce Workshop and then copy the changes over to GitHub.  If you prefer working in Perforce then sign up at the link below and send me your user id.

    https://swarm.workshop.perforce.com/projects/p4-jenkins/


Here are the Perforce connection details if you want to sync/shelve changes:

	P4PORT:		public.perforce.com:1666
	Depot Path:	//guest/perforce_software/p4jenkins/main/...

Kind regards,
Paul
 
> 
> On 26 Mar 2015, at 18:08, Eugene <notifications@github.com> wrote:
> 
> Hi Paul,
> 
> Template workspaces don't work for us for a couple of reasons — specs need to be under version control to integrate changes between branches into them, comments are vital as they are rather large and need explanations what goes where, etc.
> 
> Your suggestions about merging this with SpecFile just gave me an idea... What if I instead extend SpecFile mode with a filter script command? I imagine this will be the most flexible — anyone can use whatever spec format they are used to, or even many of them, and write a very simple filter script to convert it to the standard p4s; or leave script command field empty and use p4s directly. And this will avoid complicating the plugin with a new mode which largely duplicates SpecFile in functionality&tests anyway.
> 
> BTW, is this the right repo to send pull requests to? I see this one has version 1.0.11 while jenkinsci/p4-jenkins is at 1.2.0.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Comment by hamstergene** [comment]
I'm thinking about environment variables. That's the standard way for communicating with arbitrary subprocesses, Jenkins already does that for "Execute shell" kind of builds.

The only two required options for `p4 client -i` are `Client:` (workspace name) and `Root:` (local path), but providing additional variables may be useful too, for example, `JENKINS_HOME` and `ITEM_FULL_NAME`.

**Comment by p4paul** [comment]
I'll wait and see what you decide.  I have some reservation with the use of Environment variables, but that mainly results from a very bad experience of Jenkins Polling implementation.  

If you can avoid their use that would be great as.  The Workspace name will be present on the right hand side of the View mapping and the Jenkins Job knows the Workspace root.  For all the other settings/options you can assume the defaults.


> On 29 Mar 2015, at 14:07, Eugene <notifications@github.com> wrote:
> 
> I'm thinking about environment variables. That's the standard way for communicating with arbitrary subprocesses, Jenkins already does that for "Execute shell" kind of builds.
> 
> The only two required options for p4 client -i are Client: (workspace name) and Root: (local path), but providing additional variables may be useful too, for example, JENKINS_HOME and ITEM_FULL_NAME.
> 
> —
> Reply to this email directly or view it on GitHub.
> 



--------------------------------------------------------------------------------
This email and any files transmitted with it are confidential and intended 
solely for the use of the individual or entity to whom they are addressed. If 
you have received this email in error please notify the system manager. Please 
note that any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of Perforce Software. Finally, 
the recipient should check this email and any attachments for the presence of 
viruses. Perforce Software accepts no liability for any damage caused by any 
virus transmitted by this email.

Perforce Software UK Ltd is registered in England and Wales as company no. 
3816019 at the following address: West Forest Gate, Wellington Road, Wokingham,
RG40 2AT, UK
--------------------------------------------------------------------------------

**Pull request closed without merging**
